## The Movie Database Project
### Working with APIs and JSON
Retreiving a single movie

In [1]:
api_key  = "api_key=8265bd1679663a7ea12ac168da84d2e8"

In [2]:
import pandas as pd
import requests
import json
import ast
import numpy as np
pd.options.display.max_columns = 30

In [3]:
movie_id = 140607

In [4]:
movie_api = "https://api.themoviedb.org/3/movie/{}?"
movie_api

'https://api.themoviedb.org/3/movie/{}?'

In [5]:
url = movie_api.format(movie_id) + api_key
url

'https://api.themoviedb.org/3/movie/140607?api_key=8265bd1679663a7ea12ac168da84d2e8'

In [6]:
r = requests.get(url)
r

In [7]:
data = r.json()
data

{'adult': False,
 'backdrop_path': '/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg',
 'belongs_to_collection': {'id': 10,
  'name': 'Star Wars Collection',
  'poster_path': '/gq5Wi7i4SF3lo4HHkJasDV95xI9.jpg',
  'backdrop_path': '/d8duYyyC9J5T825Hg7grmaabfxQ.jpg'},
 'budget': 245000000,
 'genres': [{'id': 12, 'name': 'Adventure'},
  {'id': 28, 'name': 'Action'},
  {'id': 878, 'name': 'Science Fiction'},
  {'id': 14, 'name': 'Fantasy'}],
 'homepage': 'http://www.starwars.com/films/star-wars-episode-vii',
 'id': 140607,
 'imdb_id': 'tt2488496',
 'original_language': 'en',
 'original_title': 'Star Wars: The Force Awakens',
 'overview': 'Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.',
 'popularity': 66.228,
 'poster_path': '/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg',
 'production_companies': [{'id': 1,
   'logo_path': '/o86DbpburjxrqAzEDhXZcyE8pDb.png',
   'name': 'Lucasfilm Ltd.',
   'origin_country': 'US'},
  {'id': 11461,
   'logo_path': '/p9FoEt5shEKRWRKVIlvFaEmRnun.png',
   'name': 'Bad Robot',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '2015-12-15',
 'revenue': 2068223624,
 'runtime': 136,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'}],
 'status': 'Released',
 'tagline': 'Every generation has a story.',
 'title': 'Star Wars: The Force Awakens',
 'video': False,
 'vote_average': 7.309,
 'vote_count': 17521}

In [8]:
pd.Series(data)

adult                                                                False
backdrop_path                             /8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg
belongs_to_collection    {'id': 10, 'name': 'Star Wars Collection', 'po...
budget                                                           245000000
genres                   [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...
homepage                 http://www.starwars.com/films/star-wars-episod...
id                                                                  140607
imdb_id                                                          tt2488496
original_language                                                       en
original_title                                Star Wars: The Force Awakens
overview                 Thirty years after defeating the Galactic Empi...
popularity                                                          66.228
poster_path                               /wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg
production_companies     [{'id': 1, 'logo_path': '/o86DbpburjxrqAzEDhXZ...
production_countries     [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                    2015-12-15
revenue                                                         2068223624
runtime                                                                136
spoken_languages         [{'english_name': 'English', 'iso_639_1': 'en'...
status                                                            Released
tagline                                      Every generation has a story.
title                                         Star Wars: The Force Awakens
video                                                                False
vote_average                                                         7.309
vote_count                                                           17521
dtype: object

In [9]:
df = pd.Series(data).to_frame().T
df

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,140607,tt2488496,en,Star Wars: The Force Awakens,Thirty years after defeating the Galactic Empi...,66.228,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,"[{'id': 1, 'logo_path': '/o86DbpburjxrqAzEDhXZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2015-12-15,2068223624,136,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Every generation has a story.,Star Wars: The Force Awakens,False,7.309,17521

In [10]:
pd.json_normalize(data, sep = "_")

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,belongs_to_collection_id,belongs_to_collection_name,belongs_to_collection_poster_path,belongs_to_collection_backdrop_path
0,False,/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg,245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,140607,tt2488496,en,Star Wars: The Force Awakens,Thirty years after defeating the Galactic Empi...,66.228,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,"[{'id': 1, 'logo_path': '/o86DbpburjxrqAzEDhXZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2015-12-15,2068223624,136,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Every generation has a story.,Star Wars: The Force Awakens,False,7.309,17521,10,Star Wars Collection,/gq5Wi7i4SF3lo4HHkJasDV95xI9.jpg,/d8duYyyC9J5T825Hg7grmaabfxQ.jpg

In [11]:
pd.json_normalize(data = data, record_path = "genres", meta = "title")

    id             name                         title
0   12        Adventure  Star Wars: The Force Awakens
1   28           Action  Star Wars: The Force Awakens
2  878  Science Fiction  Star Wars: The Force Awakens
3   14          Fantasy  Star Wars: The Force Awakens

In [12]:
pd.json_normalize(data = data, record_path = "production_companies", meta = "title")

,id,logo_path,name,origin_country,title
0,1,/o86DbpburjxrqAzEDhXZcyE8pDb.png,Lucasfilm Ltd.,US,Star Wars: The Force Awakens
1,11461,/p9FoEt5shEKRWRKVIlvFaEmRnun.png,Bad Robot,US,Star Wars: The Force Awakens

#### Retrieving movies within a range

In [13]:
discover_api = "https://api.themoviedb.org/3/discover/movie?"

In [14]:
query = "&primary_release_date.gte=2020-01-01&primary_release_date.lte=2021-01-01"

In [15]:
url = discover_api+api_key+query

In [16]:
data = requests.get(url).json()
data

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/qjGrUmKW78MCFG8PTLDBp67S27p.jpg',
   'genre_ids': [16, 28, 12, 14],
   'id': 635302,
   'original_language': 'ja',
   'original_title': '劇場版「鬼滅の刃」無限列車編',
   'overview': "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
   'popularity': 311.592,
   'poster_path': '/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg',
   'release_date': '2020-10-16',
   'title': 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train',
   'video': False,
   'vote_average': 8.3,
   'vote_count': 2811},
  {'adult': False,
   'backdrop_path': '/6hgItrYQEG33y0I7yP2SRl2ei4w.jpg',
   'genre_ids': [10749, 18],
   'id': 613504,
   'original_language': 'en',
   'original_title': 'After We Collided',
   'overview': 'Tessa finds herself struggling with her complicated relationship with Hardin; she faces a dilemma that could change their lives forever.',
   'popularity': 115.737,
   'poster_path': '/kiX7UYfOpYrMFSAGbI6j1pFkLzQ.jpg',
   'release_date': '2020-09-02',
   'title': 'After We Collided',
   'video': False,
   'vote_average': 7.2,
   'vote_count': 4790},
  {'adult': False,
   'backdrop_path': '/dIibeeq4QMay5bTJ2vjr72IFFRo.jpg',
   'genre_ids': [14, 12, 35],
   'id': 589754,
   'original_language': 'ru',
   'original_title': 'Последний богатырь: Корень зла',
   'overview': 'Peace and tranquility have set in Belogorie. The evil was defeated and Ivan is now enjoying his well-deserved fame. He is surrounded by his family, friends and small wonders from the modern world that help him lead a comfortable life. Luckily, he has his Magic Sword to cut a gap between the worlds to get some supplies quite regularly. But when an ancient evil rises and the existence of the magic world is put to danger, Ivan has to team up with his old friends and his new rivals. They will set out on a long journey beyond the known world to find a way to defeat the enemies and to return peace to Belogorie.',
   'popularity': 130.889,
   'poster_path': '/5VJSIAhSn4qUsg5nOj4MhQhF5wQ.jpg',
   'release_date': '2021-01-01',
   'title': 'The Last Warrior: Root of Evil',
   'video': False,
   'vote_average': 7,
   'vote_count': 119},
  {'adult': False,
   'backdrop_path': '/ytTQoYkdpsgtfDWrNFCei8Mfbxu.jpg',
   'genre_ids': [16, 10751, 12, 14, 35],
   'id': 529203,
   'original_language': 'en',
   'original_title': 'The Croods: A New Age',
   'overview': "Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
   'popularity': 112.835,
   'poster_path': '/tbVZ3Sq88dZaCANlUcewQuHQOaE.jpg',
   'release_date': '2020-11-25',
   'title': 'The Croods: A New Age',
   'video': False,
   'vote_average': 7.5,
   'vote_count': 3174},
  {'adult': False,
   'backdrop_path': '/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg',
   'genre_ids': [28, 878, 35, 10751],
   'id': 454626,
   'original_language': 'en',
   'original_title': 'Sonic the Hedgehog',
   'overview': 'Powered with incredible speed, Sonic The Hedgehog embraces his new home on Earth. That is, until Sonic sparks the attention of super-uncool evil genius Dr. Robotnik. Now it’s super-villain vs. super-sonic in an all-out race across the globe to stop Robotnik from using Sonic’s unique power for world domination.',
   'popularity': 107.513,
   'poster_path': '/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg',
   'release_date': '2020-02-12',
   'title': 'Sonic the Hedgehog',
   'video': False,
   'vote_average': 7.4,
   'vote_count': 8407},
  {'adult': False,
   'backdrop_path': '/wu1uilmhM4TdluKi2ytfz8gidHf.jpg',
   'genre_ids': [10751, 16, 14, 12, 35],
   'id': 400160,
   'original_language': 'en',
   'original_title': 'The SpongeBob Movie: Sponge on the Run',
   'overview': 'When his best friend Gary is suddenly snatched away, SpongeBob takes Patrick on a madcap mission far beyond Bikini Bottom to save their pink-shelled pal.',
   'popularity': 90.685,
   'poster_path': '/jlJ8nDhMhCYJuzOw3f52CP1W8MW.jpg',
   'release_date': '2020-08-14',
   'title': 'The SpongeBob Movie: Sponge on the Run',
   'video': False,
   'vote_average': 7.6,
   'vote_count': 2558},
  {'adult': False,
   'backdrop_path': '/z8sNNjEXEpZNQCHCuo3QH8kK00t.jpg',
   'genre_ids': [10749],
   'id': 665142,
   'original_language': 'ko',
   'original_title': '어린 이모 3',
   'overview': "Seok-yeong has been living with his father ever since his parents got divorced when he was young. His father, Joong-nam, would always introduce his new girlfriends to Seok-yeong, but Seok-yeong didn't like running into strangers in his house. At the same time, Seok-yeong feels more comfortable with women older than him.  One day, Joong-nam says he's going to marry his new girlfriend, Gyeo-won. At a family dinner, Seok-yeong feels attracted to Gyeo-won's sister, Gyeo-woon, but he has to call her 'aunt'",
   'popularity': 66.597,
   'poster_path': '/qD7kT9LysayisTiCrdFyhZWIuK1.jpg',
   'release_date': '2020-01-02',
   'title': 'Young Aunt 3',
   'video': False,
   'vote_average': 6.7,
   'vote_count': 3},
  {'adult': False,
   'backdrop_path': '/adlZgxAudw3ZPA0HUcDzSTKrH8B.jpg',
   'genre_ids': [16, 10751, 12, 10770, 14, 28],
   'id': 755812,
   'original_language': 'fr',
   'original_title': 'Miraculous World : New York, les héros unis',
   'overview': 'During a school field trip, Ladybug and Cat Noir meet the American superheroes, whom they have to save from an akumatised super-villain. They discover that Miraculous exist in the United States too.',
   'popularity': 106.443,
   'poster_path': '/9YbyvcrHmY2SVbdfXpb8mC4Fy0g.jpg',
   'release_date': '2020-09-25',
   'title': 'Miraculous World: New York, United HeroeZ',
   'video': False,
   'vote_average': 8.2,
   'vote_count': 947},
  {'adult': False,
   'backdrop_path': '/uozb2VeD87YmhoUP1RrGWfzuCrr.jpg',
   'genre_ids': [28, 80],
   'id': 495764,
   'original_language': 'en',
   'original_title': 'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)',
   'overview': 'Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.',
   'popularity': 79.807,
   'poster_path': '/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg',
   'release_date': '2020-02-05',
   'title': 'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)',
   'video': False,
   'vote_average': 7,
   'vote_count': 9121},
  {'adult': False,
   'backdrop_path': '/yzpCv8CCWondN7O5au1KGiqnC3A.jpg',
   'genre_ids': [28, 12, 14],
   'id': 464052,
   'original_language': 'en',
   'original_title': 'Wonder Woman 1984',
   'overview': 'A botched store robbery places Wonder Woman in a global battle against a powerful and mysterious ancient force that puts her powers in jeopardy.',
   'popularity': 93.945,
   'poster_path': '/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg',
   'release_date': '2020-12-16',
   'title': 'Wonder Woman 1984',
   'video': False,
   'vote_average': 6.5,
   'vote_count': 7247},
  {'adult': False,
   'backdrop_path': '/8K9w7juIRSEFM49ASyU2ROf30nP.jpg',
   'genre_ids': [10749],
   'id': 685833,
   'original_language': 'ko',
   'original_title': '목공소에서 생긴 일',
   'overview': 'A rumour spread out all over the neighborhood. Yeon-joo, a beautiful, entertaining SNS celebrity, and also a woodworker is being watched and admired by Do-shik.  He decides to ask her for a date one weekend. Do-shik appeared and grasped Yeon-joo without her noticing him.  Meanwhile, the clueless, naïve, and honest bookkeeper of the carpenter shop is keeping two huge secrets no one would even thought of.  Finally, the great secret of Yeon-joo and Tae-ju is revealed, turning the tables around.',
   'popularity': 62.43,
   'poster_path': '/bMhxD4DKRJM1dydluvsS5aL2Tci.jpg',
   'release_date': '2020-03-05',
   'title': "What Happened at the Carpenter's Shop",
   'video': False,
   'vote_average': 6,
   'vote_count': 2},
  {'adult': False,
   'backdrop_path': '/buop8brXQ8gGiOPrVTxZZUqE8Oa.jpg',
   'genre_ids': [27, 53, 9648],
   'id': 723072,
   'original_language': 'en',
   'original_title': 'Host',
   'overview': 'Six friends hire a medium to hold a séance via Zoom during lockdown — but they get far more than they bargained for as things quickly go wrong. When an evil spirit starts invading their homes, they begin to realize they might not survive the night.',
   'popularity': 83.798,
   'poster_path': '/h7dZpJDORYs5c56dydbrLFkEXpE.jpg',
   'release_date': '2020-12-04',
   'title': 'Host',
   'video': False,
   'vote_average': 6.5,
   'vote_count': 637},
  {'adult': False,
   'backdrop_path': '/jtIEiNgADgLiLEnQHaadheAZ943.jpg',
   'genre_ids': [10749, 35, 16],
   'id': 670327,
   'original_language': 'ja',
   'original_title': 'まるだせ金太狼',
   'overview': 'Makoto\'s grandfather was the principal of the great Onodera Academy, and when he passed away, he left Makoto and his school staff with one very important will - "The one man who is able to seduce Makoto with his superb sexual techniques will be given the right to take over as Onodera Academy\'s new principal!" Because of this ridiculous last request, Makoto is now every faculty member\'s target for sexual harassment! Desperate to protect his virginity, Makoto seeks help from his childhood friend (and the man who he has always loved), Kintaro.',
   'popularity': 89.7,
   'poster_path': '/70gildhMU2bX8D9zMbDylZBWpeY.jpg',
   'release_date': '2020-12-11',
   'title': 'Marudase Kintarou',
   'video': False,
   'vote_average': 6,
   'vote_count': 1},
  {'adult': False,
   'backdrop_path': '/z8TvnEVRenMSTemxYZwLGqFofgF.jpg',
   'genre_ids': [28, 14, 12],
   'id': 458576,
   'original_language': 'en',
   'original_title': 'Monster Hunter',
   'overview': 'A portal transports Cpt. Artemis and an elite unit of soldiers to a strange world where powerful monsters rule with deadly ferocity. Faced with relentless danger, the team encounters a mysterious hunter who may be their only hope to find a way home.',
   'popularity': 83.669,
   'poster_path': '/1UCOF11QCw8kcqvce8LKOO6pimh.jpg',
   'release_date': '2020-12-03',
   'title': 'Monster Hunter',
   'video': False,
   'vote_average': 6.7,
   'vote_count': 2755},
  {'adult': False,
   'backdrop_path': '/zMrk2G3XsnfYKiIp1NEfdtvDyBH.jpg',
   'genre_ids': [12, 14, 18, 28],
   'id': 337401,
   'original_language': 'en',
   'original_title': 'Mulan',
   'overview': 'When the Emperor of China issues a decree that one man per family must serve in the Imperial Chinese Army to defend the country from Huns, Hua Mulan, the eldest daughter of an honored warrior, steps in to take the place of her ailing father. She is spirited, determined and quick on her feet. Disguised as a man by the name of Hua Jun, she is tested every step of the way and must harness her innermost strength and embrace her true potential.',
   'popularity': 84.194,
   'poster_path': '/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg',
   'release_date': '2020-09-04',
   'title': 'Mulan',
   'video': False,
   'vote_average': 6.9,
   'vote_count': 5918},
  {'adult': False,
   'backdrop_path': '/mxVpkHclXPgWxo62SJ0a0YcUzgC.jpg',
   'genre_ids': [10751, 14, 12, 35],
   'id': 654028,
   'original_language': 'en',
   'original_title': 'The Christmas Chronicles: Part Two',
   'overview': 'Kate Pierce is reluctantly spending Christmas with her mom’s new boyfriend and his son Jack. But when the North Pole and Christmas are threatened to be destroyed, Kate and Jack are unexpectedly pulled into a new adventure with Santa Claus.',
   'popularity': 84.934,
   'poster_path': '/6sG0kbEvAi3RRLcGGU5h8l3qAPa.jpg',
   'release_date': '2020-11-18',
   'title': 'The Christmas Chronicles: Part Two',
   'video': False,
   'vote_average': 6.5,
   'vote_count': 823},
  {'adult': False,
   'backdrop_path': '/oKqsZr4Jq1Y3fPZ0ufgzUs2ToK2.jpg',
   'genre_ids': [53, 27],
   'id': 532870,
   'original_language': 'en',
   'original_title': 'Run Sweetheart Run',
   'overview': 'A woman runs for her life though the streets of Los Angeles after her blind date suddenly turns violent.',
   'popularity': 97.552,
   'poster_path': '/9xf3aiAxjx2H34EwwVFFlOrr0nt.jpg',
   'release_date': '2020-01-27',
   'title': 'Run Sweetheart Run',
   'video': False,
   'vote_average': 5.9,
   'vote_count': 73},
  {'adult': False,
   'backdrop_path': '/8rIoyM6zYXJNjzGseT3MRusMPWl.jpg',
   'genre_ids': [12, 14, 35],
   'id': 531219,
   'original_language': 'en',
   'original_title': "Roald Dahl's The Witches",
   'overview': "In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the world's Grand High Witch has gathered.",
   'popularity': 68.213,
   'poster_path': '/b1C0FuXp4wiPmHLVKq4kwtDMgK6.jpg',
   'release_date': '2020-10-25',
   'title': "Roald Dahl's The Witches",
   'video': False,
   'vote_average': 6.4,
   'vote_count': 2382},
  {'adult': False,
   'backdrop_path': '/hdXQxlD4mep7qtC5TsvhIt840OV.jpg',
   'genre_ids': [16, 28, 12, 878],
   'id': 703771,
   'original_language': 'en',
   'original_title': 'Deathstroke: Knights & Dragons - The Movie',
   'overview': 'The assassin Deathstroke tries to save his family from the wrath of H.I.V.E. and the murderous Jackal.',
   'popularity': 89.45,
   'poster_path': '/vFIHbiy55smzi50RmF8LQjmpGcx.jpg',
   'release_date': '2020-08-04',
   'title': 'Deathstroke: Knights & Dragons - The Movie',
   'video': False,
   'vote_average': 6.9,
   'vote_count': 375},
  {'adult': False,
   'backdrop_path': '/il9nvQH3f92n5bBKJfpjfaHXFYi.jpg',
   'genre_ids': [28, 80, 18, 12, 53],
   'id': 539885,
   'original_language': 'en',
   'original_title': 'Ava',
   'overview': 'A black ops assassin is forced to fight for her own survival after a job goes dangerously wrong.',
   'popularity': 72.621,
   'poster_path': '/qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg',
   'release_date': '2020-07-02',
   'title': 'Ava',
   'video': False,
   'vote_average': 5.8,
   'vote_count': 2115}],
 'total_pages': 1589,
 'total_results': 31763}

In [17]:
pd.DataFrame(data)

,page,results,total_pages,total_results
0,1,"{'adult': False, 'backdrop_path': '/qjGrUmKW78...",1589,31763
1,1,"{'adult': False, 'backdrop_path': '/6hgItrYQEG...",1589,31763
2,1,"{'adult': False, 'backdrop_path': '/dIibeeq4QM...",1589,31763
3,1,"{'adult': False, 'backdrop_path': '/ytTQoYkdps...",1589,31763
4,1,"{'adult': False, 'backdrop_path': '/stmYfCUGd8...",1589,31763
5,1,"{'adult': False, 'backdrop_path': '/wu1uilmhM4...",1589,31763
6,1,"{'adult': False, 'backdrop_path': '/z8sNNjEXEp...",1589,31763
7,1,"{'adult': False, 'backdrop_path': '/adlZgxAudw...",1589,31763
8,1,"{'adult': False, 'backdrop_path': '/uozb2VeD87...",1589,31763
9,1,"{'adult': False, 'backdrop_path': '/yzpCv8CCWo...",1589,31763
10,1,"{'adult': False, 'backdrop_path': '/8K9w7juIRS...",1589,31763
11,1,"{'adult': False, 'backdrop_path': '/buop8brXQ8...",1589,31763
12,1,"{'adult': False, 'backdrop_path': '/jtIEiNgADg...",1589,31763
13,1,"{'adult': False, 'backdrop_path': '/z8TvnEVRen...",1589,31763
14,1,"{'adult': False, 'backdrop_path': '/zMrk2G3Xsn...",1589,31763
15,1,"{'adult': False, 'backdrop_path': '/mxVpkHclXP...",1589,31763
16,1,"{'adult': False, 'backdrop_path': '/oKqsZr4Jq1...",1589,31763
17,1,"{'adult': False, 'backdrop_path': '/8rIoyM6zYX...",1589,31763
18,1,"{'adult': False, 'backdrop_path': '/hdXQxlD4me...",1589,31763
19,1,"{'adult': False, 'backdrop_path': '/il9nvQH3f9...",1589,31763

In [18]:
pd.DataFrame(data["results"])

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/qjGrUmKW78MCFG8PTLDBp67S27p.jpg,"[16, 28, 12, 14]",635302,ja,劇場版「鬼滅の刃」無限列車編,"Tanjirō Kamado, joined with Inosuke Hashibira,...",311.592,/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg,2020-10-16,Demon Slayer -Kimetsu no Yaiba- The Movie: Mug...,False,8.3,2811
1,False,/6hgItrYQEG33y0I7yP2SRl2ei4w.jpg,"[10749, 18]",613504,en,After We Collided,Tessa finds herself struggling with her compli...,115.737,/kiX7UYfOpYrMFSAGbI6j1pFkLzQ.jpg,2020-09-02,After We Collided,False,7.2,4790
2,False,/dIibeeq4QMay5bTJ2vjr72IFFRo.jpg,"[14, 12, 35]",589754,ru,Последний богатырь: Корень зла,Peace and tranquility have set in Belogorie. T...,130.889,/5VJSIAhSn4qUsg5nOj4MhQhF5wQ.jpg,2021-01-01,The Last Warrior: Root of Evil,False,7.0,119
3,False,/ytTQoYkdpsgtfDWrNFCei8Mfbxu.jpg,"[16, 10751, 12, 14, 35]",529203,en,The Croods: A New Age,"Searching for a safer habitat, the prehistoric...",112.835,/tbVZ3Sq88dZaCANlUcewQuHQOaE.jpg,2020-11-25,The Croods: A New Age,False,7.5,3174
4,False,/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg,"[28, 878, 35, 10751]",454626,en,Sonic the Hedgehog,"Powered with incredible speed, Sonic The Hedge...",107.513,/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg,2020-02-12,Sonic the Hedgehog,False,7.4,8407
5,False,/wu1uilmhM4TdluKi2ytfz8gidHf.jpg,"[10751, 16, 14, 12, 35]",400160,en,The SpongeBob Movie: Sponge on the Run,When his best friend Gary is suddenly snatched...,90.685,/jlJ8nDhMhCYJuzOw3f52CP1W8MW.jpg,2020-08-14,The SpongeBob Movie: Sponge on the Run,False,7.6,2558
6,False,/z8sNNjEXEpZNQCHCuo3QH8kK00t.jpg,[10749],665142,ko,어린 이모 3,Seok-yeong has been living with his father eve...,66.597,/qD7kT9LysayisTiCrdFyhZWIuK1.jpg,2020-01-02,Young Aunt 3,False,6.7,3
7,False,/adlZgxAudw3ZPA0HUcDzSTKrH8B.jpg,"[16, 10751, 12, 10770, 14, 28]",755812,fr,"Miraculous World : New York, les héros unis","During a school field trip, Ladybug and Cat No...",106.443,/9YbyvcrHmY2SVbdfXpb8mC4Fy0g.jpg,2020-09-25,"Miraculous World: New York, United HeroeZ",False,8.2,947
8,False,/uozb2VeD87YmhoUP1RrGWfzuCrr.jpg,"[28, 80]",495764,en,Birds of Prey (and the Fantabulous Emancipatio...,"Harley Quinn joins forces with a singer, an as...",79.807,/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg,2020-02-05,Birds of Prey (and the Fantabulous Emancipatio...,False,7.0,9121
9,False,/yzpCv8CCWondN7O5au1KGiqnC3A.jpg,"[28, 12, 14]",464052,en,Wonder Woman 1984,A botched store robbery places Wonder Woman in...,93.945,/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg,2020-12-16,Wonder Woman 1984,False,6.5,7247
10,False,/8K9w7juIRSEFM49ASyU2ROf30nP.jpg,[10749],685833,ko,목공소에서 생긴 일,A rumour spread out all over the neighborhood....,62.430,/bMhxD4DKRJM1dydluvsS5aL2Tci.jpg,2020-03-05,What Happened at the Carpenter's Shop,False,6.0,2
11,False,/buop8brXQ8gGiOPrVTxZZUqE8Oa.jpg,"[27, 53, 9648]",723072,en,Host,Six friends hire a medium to hold a séance via...,83.798,/h7dZpJDORYs5c56dydbrLFkEXpE.jpg,2020-12-04,Host,False,6.5,637
12,False,/jtIEiNgADgLiLEnQHaadheAZ943.jpg,"[10749, 35, 16]",670327,ja,まるだせ金太狼,Makoto's grandfather was the principal of the ...,89.700,/70gildhMU2bX8D9zMbDylZBWpeY.jpg,2020-12-11,Marudase Kintarou,False,6.0,1
13,False,/z8TvnEVRenMSTemxYZwLGqFofgF.jpg,"[28, 14, 12]",458576,en,Monster Hunter,A portal transports Cpt. Artemis and an elite ...,83.669,/1UCOF11QCw8kcqvce8LKOO6pimh.jpg,2020-12-03,Monster Hunter,False,6.7,2755
14,False,/zMrk2G3XsnfYKiIp1NEfdtvDyBH.jpg,"[12, 14, 18, 28]",337401,en,Mulan,When the Emperor of China issues a decree that...,84.194,/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg,2020-09-04,Mulan,False,6.9,5918
15,False,/mxVpkHclXPgWxo62SJ0a0YcUzgC.jpg,"[10751, 14, 12, 35]",654028,en,The Christmas Chronicles: Part Two,Kate Pierce is reluctantly spending Christmas ...,84.934,/6sG0kbEvAi3RRLcGGU5h8l3qAPa.jpg,2020-11-18,The Christmas Chronicles: Part Two,False,6.5,823
16,False,/oKqsZr4Jq1Y3fPZ0ufgzUs2ToK2.jpg,"[53, 27]",532870,en,Run Sweetheart Run,A woman runs for her life though the streets o...,97.552,/9xf3aiAxjx2H34EwwVFFlOrr0nt.jpg,2020-01-27,Run Sweetheart Run,False,5.9,73
17,False,/8rIoyM6zYXJNjzGseT3MRusMPWl.jpg,"[12, 14, 35]",531219,en,Roald Dahl's The Witches,"In late 1967, a young orphaned boy goes to liv...",68.213,/b1C0FuXp4wiPmHLVKq4kwtDMgK6.jpg,2020-10-25,Roald Dahl's The Witches,False,6.4,2382
18,False,/hdXQxlD4mep7qtC5TsvhIt840OV.jpg,"[16, 28, 12, 878]",703771,en,Deathstroke: Knights & Dragons - The Movie,The assassin Deathstroke tries to save his fam...,89.450,/vFIHbiy55smzi50RmF8LQjmpGcx.jpg,2020-08-04,Deathstroke: Knights & Dragons - The Movie,False,6.9,375
19,False,/il9nvQH3f92n5bBKJfpjfaHXFYi.jpg,"[28, 80, 18, 12, 53]",539885,en,Ava,A black ops assassin is forced to fight for he...,72.621,/qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg,2020-07-02,Ava,False,5.8,2115

### Importing and saving movies dataset

In [19]:
movie_id = [0, 299534, 19995, 140607, 299536, 597, 135397,
            420818, 24428, 168259, 99861, 284054, 12445,
            181808, 330457, 351286, 109445, 321612, 260513]

In [20]:
basic_url = 'https://api.themoviedb.org/3/movie/{}?{}'

In [21]:
json_list = []
for movie in movie_id:
    url = basic_url.format(movie, api_key)
    r = requests.get(url)
    if r.status_code != 200:
        continue
    else:
        data = r.json()
        json_list.append(data) 
df = pd.DataFrame(json_list)

In [22]:
requests.get(basic_url.format(0, api_key)).status_code

404

In [23]:
df

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",356000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",https://www.marvel.com/movies/avengers-endgame,299534,tt4154796,en,Avengers: Endgame,After the devastating events of Avengers: Infi...,134.894,/or06FN3Dka5tukK1e9sl16pB3iy.jpg,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2019-04-24,2797800564,181,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Avenge the fallen.,Avengers: Endgame,False,8.276,22212
1,False,/Yc9q6QuWrMp9nuDm5R8ExNqbEq.jpg,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.avatar.com/movies/avatar,19995,tt0499549,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",968.722,/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg,"[{'id': 25, 'logo_path': '/qZCc1lty5FzX30aOCVR...","[{'iso_3166_1': 'US', 'name': 'United States o...",2009-12-15,2920357254,162,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Enter the world of Pandora.,Avatar,False,7.536,26769
2,False,/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,140607,tt2488496,en,Star Wars: The Force Awakens,Thirty years after defeating the Galactic Empi...,66.228,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,"[{'id': 1, 'logo_path': '/o86DbpburjxrqAzEDhXZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2015-12-15,2068223624,136,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Every generation has a story.,Star Wars: The Force Awakens,False,7.309,17521
3,False,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.marvel.com/movies/avengers-infinit...,299536,tt4154756,en,Avengers: Infinity War,As the Avengers and their allies have continue...,218.330,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2018-04-25,2046239637,149,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,An entire universe. Once and for all.,Avengers: Infinity War,False,8.267,25851
4,False,/3WjbxaqYB4vAbdUfdr5vbglD2JZ.jpg,None,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",,597,tt0120338,en,Titanic,101-year-old Rose DeWitt Bukater tells the sto...,111.463,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,"[{'id': 4, 'logo_path': '/gz66EfNoYPqHTYI4q9UE...","[{'iso_3166_1': 'US', 'name': 'United States o...",1997-11-18,2187463944,194,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Nothing on Earth could come between them.,Titanic,False,7.900,21878
5,False,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",150000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.jurassicworld.com/,135397,tt0369610,en,Jurassic World,Twenty-two years after the events of Jurassic ...,80.946,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,"[{'id': 33, 'logo_path': '/8lvHyhjr8oUKOOy2dKX...","[{'iso_3166_1': 'US', 'name': 'United States o...",2015-06-06,1671713208,124,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The park is open.,Jurassic World,False,6.676,18624
6,False,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,"{'id': 762512, 'name': 'The Lion King (Reboot)...",260000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",https://movies.disney.com/the-lion-king-2019,420818,tt6105098,en,The Lion King,"Simba idolizes his father, King Mufasa, and ta...",88.186,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,"[{'id': 2, 'logo_path': '/wdrCwmRnLFJhEoH8GSfy...","[{'iso_3166_1': 'US', 'name': 'United States o...",2019-07-12,1667635327,118,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The King has Returned.,The Lion King,False,7.135,8775
7,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.marvel.com/movies/the-avengers,24428,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,127.867,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2012-04-25,1518815515,143,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Some assembly required.,The Avengers,False,7.708,27860
8,False,/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg,"{'id': 9485, 'name': 'The Fast and the Furious...",190000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",https://www.thefastsaga.com/fast-saga/ff7,168259,tt2820852,en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,67.968,/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg,"[{'id': 33, 'logo_path': '/8lvHyhjr8oUKOOy2dKX...","[{'iso_3166_1': 'US', 'name': 'United States o...",2015-04-01,1515047671,137,"[{'english_name': 'Arabic', 'iso_639_1': 'ar',...",Released,Vengeance hits home,Furious 7,False,7.235,9408
9,False,/6YwkGolwdOMNpbTOmLjoehlVWs5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",365000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,tt2395427,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,120.073,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2015-04-22,1405403694,141,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,A New Age Has Come.,Avengers: Age of Ultron,False,7.286,20657
10,False,/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg,"{'id': 529892, 'name': 'Black Panther Collecti...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.marvel.com/movies/black-panther,284054,tt1825683,en,Black Panther,"King T'Challa returns home to the reclusive, t...",239.558,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2018-02-13,1347597973,135,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Long live the king.,Black Panther,False,7.400,19956
11,False,/n5A7brJCjejceZmHyujwUTVgQNC.jpg,"{'id': 1241, 'name': 'Harry Potter Collection'...",125000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",https://www.warnerbros.com/movies/harry-potter...,12445,tt1201607,en,Harry Potter and the Deathly Hallows: Part 2,"Harry, Ron and Hermione continue their quest t...",200.239,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,"[{'id': 174, 'logo_path': '/IuAlhI9eVC9Z8UQWOI...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2011-07-07,1341511219,130,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,It all ends here.,Harry Potter and the Deathly Hallows: Part 2,False,8.115,17987
12,False,/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",200000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.starwars.com/films/star-wars-episo...,181808,tt2527336,en,Star Wars: The Last Jedi,Rey develops her newly discovered abilities wi...,54.389,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,"[{'id': 1, 'logo_path': '/o86DbpburjxrqAzEDhXZ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2017-12-13,1332698830,152,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Darkness rises... and light to meet it,Star Wars: The Last Jedi,False,6.851,13517
13,False,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",https://movies.disney.com/frozen-2,330457,tt4520988,en,Frozen II,"Elsa, Anna, Kristoff and Olaf head far into th...",97.932,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,"[{'id': 2, 'logo_path': '/wdrCwmRnLFJhEoH8GSfy...","[{'iso_3166_1': 'US', 'name': 'United States o...",2019-11-20,1450026933,103,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The past is not what it seems.,Frozen II,False,7.289,8535
14,False,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",170000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.jurassicworld.com,351286,tt4881806,en,Jurassic World: Fallen Kingdom,When the island's dormant volcano begins roari...,75.544,/c9XxwwhPHdaImA2f1WEfEsbhaFB.jpg,"[{'id': 33, 'logo_path': '/8lvHyhjr8oUKOOy2dKX...","[{'iso_3166_1': 'US', 'name': 'United States o...",2018-06-06,1310466296,129,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The park is gone.,Jurassic World: Fallen Kingdom,False,6.558,10362
15,False,/fydUcbkqLyESCFa9U5XKqi8dIVj.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",http://movies.disney.com/frozen,109445,tt2294629,en,Frozen,Young princess Anna of Arendelle dreams about ...,93.467,/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg,"[{'id': 2, 'logo_path': '/wdrCwmRnLFJhEoH8GSfy...","[{'iso_3166_1': 'US', 'name': 'United States o...",2013-11-20,1274219009,102,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Only the act of true love will thaw a frozen h...,Frozen,False,7.253,14746
16,False,/phhbtV5BEdn4TYLTMKFwYz2VSNl.jpg,None,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://movies.disney.com/beauty-and-the-beast-...,321612,tt2771200,en,Beauty and the Beast,A live-action adaptation of Disney's version o...,69.124,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,"[{'id': 2, 'logo_path': '/wdrCwmRnLFJhEoH8GSfy...","[{'iso_3166_1': 'US', 'name': 'United States o...",2017-03-16,1263521126,129,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Be our guest.,Beauty and the Beast,False,6.968,14387
17,False,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,"{'id': 468222, 'name': 'The Incredibles Collec...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://movies.disney.com/incredibles-2,260513,tt3606756,en,Incredibles 2,Elastigirl springs into action to save the day...,72.845,/aTbRJHCrQwceSS5b8LYj7hC654I.jpg,"[{'id': 2, 'logo_path': '/wdrCwmRnLFJhEoH8GSfy...","[{'iso_3166_1': 'US', 'name': 'United States o...",2018-06-14,1242805359,118,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Back to work.,Incredibles 2,False,7.499,11372

In [24]:
df = df.loc[:, ["title", "id", "revenue", "genres", "belongs_to_collection", 
"runtime"]].sort_values(by = "revenue",ascending = False)

df

,title,id,revenue,genres,belongs_to_collection,runtime
1,Avatar,19995,2920357254,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 87096, 'name': 'Avatar Collection', 'po...",162
0,Avengers: Endgame,299534,2797800564,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...","{'id': 86311, 'name': 'The Avengers Collection...",181
4,Titanic,597,2187463944,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",None,194
2,Star Wars: The Force Awakens,140607,2068223624,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","{'id': 10, 'name': 'Star Wars Collection', 'po...",136
3,Avengers: Infinity War,299536,2046239637,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","{'id': 86311, 'name': 'The Avengers Collection...",149
5,Jurassic World,135397,1671713208,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 328, 'name': 'Jurassic Park Collection'...",124
6,The Lion King,420818,1667635327,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...","{'id': 762512, 'name': 'The Lion King (Reboot)...",118
7,The Avengers,24428,1518815515,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...","{'id': 86311, 'name': 'The Avengers Collection...",143
8,Furious 7,168259,1515047671,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...","{'id': 9485, 'name': 'The Fast and the Furious...",137
13,Frozen II,330457,1450026933,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...","{'id': 386382, 'name': 'Frozen Collection', 'p...",103
9,Avengers: Age of Ultron,99861,1405403694,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 86311, 'name': 'The Avengers Collection...",141
10,Black Panther,284054,1347597973,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 529892, 'name': 'Black Panther Collecti...",135
11,Harry Potter and the Deathly Hallows: Part 2,12445,1341511219,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...","{'id': 1241, 'name': 'Harry Potter Collection'...",130
12,Star Wars: The Last Jedi,181808,1332698830,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...","{'id': 10, 'name': 'Star Wars Collection', 'po...",152
14,Jurassic World: Fallen Kingdom,351286,1310466296,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 328, 'name': 'Jurassic Park Collection'...",129
15,Frozen,109445,1274219009,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...","{'id': 386382, 'name': 'Frozen Collection', 'p...",102
16,Beauty and the Beast,321612,1263521126,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",None,129
17,Incredibles 2,260513,1242805359,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...","{'id': 468222, 'name': 'The Incredibles Collec...",118

In [25]:
df.to_json("movies.json", orient = "records")

In [26]:
with open("movies.json") as f:
    data = json.load(f)

In [27]:
pd.json_normalize(data)

,title,id,revenue,genres,runtime,belongs_to_collection.id,belongs_to_collection.name,belongs_to_collection.poster_path,belongs_to_collection.backdrop_path,belongs_to_collection
0,Avatar,19995,2920357254,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",162,87096.0,Avatar Collection,/uO2yU3QiGHvVp0L5e5IatTVRkYk.jpg,/iaEsDbQPE45hQU2EGiNjXD2KWuF.jpg,NaN
1,Avengers: Endgame,299534,2797800564,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",181,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
2,Titanic,597,2187463944,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",194,NaN,NaN,NaN,NaN,NaN
3,Star Wars: The Force Awakens,140607,2068223624,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",136,10.0,Star Wars Collection,/gq5Wi7i4SF3lo4HHkJasDV95xI9.jpg,/d8duYyyC9J5T825Hg7grmaabfxQ.jpg,NaN
4,Avengers: Infinity War,299536,2046239637,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",149,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
5,Jurassic World,135397,1671713208,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",124,328.0,Jurassic Park Collection,/jcUXVtJ6s0NG0EaxllQCAUtqdr0.jpg,/njFixYzIxX8jsn6KMSEtAzi4avi.jpg,NaN
6,The Lion King,420818,1667635327,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",118,762512.0,The Lion King (Reboot) Collection,/dGpIRn4Nqi63JO1RlKxjcPbQSAw.jpg,/jIgM7YNVft0YGeXsqrh3oG5TWLx.jpg,NaN
7,The Avengers,24428,1518815515,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",143,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
8,Furious 7,168259,1515047671,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",137,9485.0,The Fast and the Furious Collection,/yvr1Ziehgps1VJyug8nnezTJRJW.jpg,/gC9BUFiROWtaMsluGYziZ6lR4OJ.jpg,NaN
9,Frozen II,330457,1450026933,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",103,386382.0,Frozen Collection,/2DdKGQYzE6D7pSvvHvM9FRzTh5r.jpg,/6QonAoIN0jhWZZWZGJswSxHzUnU.jpg,NaN
10,Avengers: Age of Ultron,99861,1405403694,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",141,86311.0,The Avengers Collection,/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg,/zuW6fOiusv4X9nnW3paHGfXcSll.jpg,NaN
11,Black Panther,284054,1347597973,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",135,529892.0,Black Panther Collection,/uVnN6KnfDuHiC8rsVsSc7kk0WRD.jpg,/yzVxUMYGKjK3GgmVI2BhmbuL9UY.jpg,NaN
12,Harry Potter and the Deathly Hallows: Part 2,12445,1341511219,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",130,1241.0,Harry Potter Collection,/eVPs2Y0LyvTLZn6AP5Z6O2rtiGB.jpg,/4gV0rKUjB1nLUdZB4zIltLvNZZr.jpg,NaN
13,Star Wars: The Last Jedi,181808,1332698830,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",152,10.0,Star Wars Collection,/gq5Wi7i4SF3lo4HHkJasDV95xI9.jpg,/d8duYyyC9J5T825Hg7grmaabfxQ.jpg,NaN
14,Jurassic World: Fallen Kingdom,351286,1310466296,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",129,328.0,Jurassic Park Collection,/jcUXVtJ6s0NG0EaxllQCAUtqdr0.jpg,/njFixYzIxX8jsn6KMSEtAzi4avi.jpg,NaN
15,Frozen,109445,1274219009,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",102,386382.0,Frozen Collection,/2DdKGQYzE6D7pSvvHvM9FRzTh5r.jpg,/6QonAoIN0jhWZZWZGJswSxHzUnU.jpg,NaN
16,Beauty and the Beast,321612,1263521126,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",129,NaN,NaN,NaN,NaN,NaN
17,Incredibles 2,260513,1242805359,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",118,468222.0,The Incredibles Collection,/xMX1jZyObVeWUxDQmt53X6jzIO4.jpg,/6oi6V1O9MJRNnfV8E9JMntmFqBD.jpg,NaN

In [28]:
pd.json_normalize(data, "genres", "title")

       id             name                 title
0      28           Action                Avatar
1      12        Adventure                Avatar
2      14          Fantasy                Avatar
3     878  Science Fiction                Avatar
4      12        Adventure     Avengers: Endgame
..    ...              ...                   ...
56  10749          Romance  Beauty and the Beast
57     28           Action         Incredibles 2
58     12        Adventure         Incredibles 2
59     16        Animation         Incredibles 2
60  10751           Family         Incredibles 2

[61 rows x 3 columns]

In [29]:
df.to_csv("movies_raw.csv", index = False)